### ISSUE TITLE
[BUG_SP] Lau error on entering last row

### ISSUE THREAD

**Issue by JDTiger** [pops64/Courseplay_FS22#28]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
finish chopping a field

**Actual behavior**
Game freezes

**Expected behavior**
game continues running, chopperharvests last row

**Screenshots**
https://youtu.be/eHIZyQL0Cro
**Courseplay version**
Version used: Current chopper branch

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

[log.txt](https://github.com/pops64/Courseplay_FS22/files/12643532/log.txt)

**Map**
Map played on.

**Vehicles/ implements involved**
Which vehicle or implement?
Mod yes/no ?

**Relevant script mods**
Mods like Autodrive or VCA and so on.

**Comment by regs1980** [comment]
https://github.com/pops64/Courseplay_FS22/issues/3#issuecomment-1722542188

**Comment by pops64** [comment]
I need debug prompts on both the chopper and unload trailer driver. Try with the latest push I added code so i can see what is going on. The error shouldn't occur ...

**Comment by JDTiger** [comment]
Ok, here are some vids and logs for you, still crashes on entering last row:

Case 1: Unloader took the wrong side prior to the last row:
[log.txt](https://github.com/pops64/Courseplay_FS22/files/12677611/log.txt)
https://youtu.be/cRNSZGzwnJE

Case 2: unloader was on the correct side on the second to last row:
[log.txt](https://github.com/pops64/Courseplay_FS22/files/12677660/log.txt)
https://youtu.be/jMkJUqaOPHE

Two different log errors depending on the side the unloader was on during the second to last row...
Which begs the question: why was he on the wrong side in the first place?

**Comment by JDTiger** [comment]
Fixed

**Comment by pops64** [comment]
Its a question of comprise on how to figure out where the fruit is. All the systems are designed around a combine which has the pipe side fixed and can store its own fruit. Which means all the methods to figure this out are not very accurate in the moment. After it drives a bit it can figure it out(CP also made its own function based on a fixed pipe side). So I had to develop a means to know which side is the right side most of the time the moment an unloadeder wants to show up. 99% of the time it will work. Multi tools can break the underlying logic(I have a plan to fix this). Grass is broken due to the function I interface to tell if fruit is at x,z doesn't count grass a fruit cause you can drive over it(I also think cut and uncut grass are still the same fruit which also break logic). So I plan to make it just be the side that won't interfere with the chopper when turning.
